[
	["AM1 - Base", [
		[],
		[],
		["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],
		["rhs_uniform_cu_ocp",[["ACE_tourniquet",4],["ACE_morphine",4],["ACE_epinephrine",1],["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_quikclot",9],["ACE_elasticBandage",2]]],
		["rhsusf_iotv_ocp_Rifleman",[["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_splint",4],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_personalAidKit",1],["ACRE_PRC343",1],["ItemcTabHCam",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["MS_Strobe_Mag_1",5,1],["SmokeShell",7,1],["rhs_mag_m67",2,1]]],
		["rhsusf_assault_eagleaiii_ocp",[]],
		"rhsusf_ach_helmet_ocp","",
		["Rangefinder","","","",[],[],""],
		["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]
	]],
	["AM1 - Base (FL)", [
		[],
		[],
		["rhsusf_weap_glock17g4","","acc_flashlight_pistol",
		"",
		["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],
		["rhs_uniform_cu_ocp",[["ACE_tourniquet",4],["ACE_morphine",4],["ACE_epinephrine",1],["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_quikclot",9],["ACE_elasticBandage",2]]],
		["rhsusf_iotv_ocp_Teamleader",[["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_splint",4],["ACE_CableTie",6],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_personalAidKit",1],["ACRE_PRC343",1],["ACRE_PRC152",1],["ACE_M26_Clacker",1],["ItemcTabHCam",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["MS_Strobe_Mag_1",5,1],["SmokeShell",8,1],["rhs_mag_m67",2,1],["SmokeShellGreen",2,1]]],
		["rhsusf_assault_eagleaiii_ocp",[["rhsusf_m112_mag",1,1]]],
		"rhsusf_ach_helmet_ocp",
		"",["Rangefinder","","","",[],[],""],
		["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]
	]],
	["AM1 - Base (SL)", [
		[],
		[],
		["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],
		["rhs_uniform_cu_ocp",[["ACE_tourniquet",4],["ACE_morphine",4],["ACE_epinephrine",1],["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_quikclot",9],["ACE_elasticBandage",2]]],
		["rhsusf_iotv_ocp_Squadleader",[["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_splint",4],["ACE_CableTie",6],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_personalAidKit",1],["ACE_M26_Clacker",1],["ACRE_PRC343",1],["ACRE_PRC152",1],["ACRE_PRC152",1],["ItemcTabHCam",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["MS_Strobe_Mag_1",5,1],["SmokeShell",5,1],["rhs_mag_m67",2,1],["SmokeShellGreen",2,1],["SmokeShellRed",1,1],["SmokeShellBlue",1,1],["Laserbatteries",1,1]]],
		["rhsusf_assault_eagleaiii_ocp",[["rhsusf_m112_mag",1,1]]],
		"rhsusf_ach_helmet_ocp",
		"",
		["Laserdesignator_01_khk_F","","","",["Laserbatteries",1],[],""],
		["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]
	]],
	["AM1 - Rifleman", [
		["rhs_weap_m4a1_blockII_d","","","rhsusf_acc_eotech_552_d",["rhs_mag_30Rnd_556x45_Mk318_PMAG",30],[],""],
		[],
		["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],
		["rhs_uniform_cu_ocp",[["ACE_tourniquet",4],["ACE_morphine",4],["ACE_epinephrine",1],["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_quikclot",9],["ACE_elasticBandage",2]]],
		["rhsusf_iotv_ocp_Rifleman",[["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_splint",4],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_personalAidKit",1],["ACRE_PRC343",1],["ItemcTabHCam",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["MS_Strobe_Mag_1",5,1],["SmokeShell",7,1],["rhs_mag_m67",3,1],["rhs_mag_30Rnd_556x45_Mk318_PMAG",2,30]]],
		["rhsusf_assault_eagleaiii_ocp",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",13,30]]],
		"rhsusf_ach_helmet_ocp",
		"",
		["Rangefinder","","","",[],[],""],
		["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]
	]],
	["AM1 - Machine Gunner", [
		["rhs_weap_m249_light_L","","","rhsusf_acc_ELCAN",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_bipod"],
		[],
		["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],
		["rhs_uniform_cu_ocp",[["ACE_tourniquet",4],["ACE_morphine",4],["ACE_epinephrine",1],["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_quikclot",9],["ACE_elasticBandage",2]]],
		["rhsusf_iotv_ocp_SAW",[["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_splint",4],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_personalAidKit",1],["ACRE_PRC343",1],["ItemcTabHCam",1],["MS_Strobe_Mag_1",5,1],["SmokeShell",6,1],["rhs_mag_m67",2,1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",1,200],["rhsusf_mag_17Rnd_9x19_FMJ",1,17]]],
		["rhsusf_assault_eagleaiii_ocp",[["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",5,200],["rhsusf_mag_17Rnd_9x19_FMJ",1,17]]],
		"rhsusf_ach_helmet_ocp",
		"",
		["Rangefinder","","","",[],[],""],
		["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]
	]],
	["AM1 - Grenadier", [
		["rhs_weap_m4a1_blockII_M203_d","","","rhsusf_acc_eotech_552_d",["rhs_mag_30Rnd_556x45_Mk318_PMAG",30],["rhs_mag_M397_HET",1],""],
		["rhs_weap_M136","","","",[],[],""],
		["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],
		["rhs_uniform_cu_ocp",[["ACE_tourniquet",4],["ACE_morphine",4],["ACE_epinephrine",1],["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_quikclot",9],["ACE_elasticBandage",2]]],
		["rhsusf_iotv_ocp_Grenadier",[["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_splint",4],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_personalAidKit",1],["ItemcTabHCam",1],["ACRE_PRC343",1],["rhsusf_mag_17Rnd_9x19_FMJ",1,17],["MS_Strobe_Mag_1",5,1],["SmokeShell",3,1],["rhs_mag_m67",3,1],["rhs_mag_30Rnd_556x45_Mk318_PMAG",4,30]]],
		["rhsusf_assault_eagleaiii_ocp",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",10,30],["rhs_mag_M397_HET",10,1],["1Rnd_Smoke_Grenade_shell",10,1],["UGL_FlareWhite_F",4,1],["UGL_FlareCIR_F",2,1],["rhs_mag_M433_HEDP",6,1]]],
		"rhsusf_ach_helmet_ocp",
		"",
		["Rangefinder","","","",[],[],""],
		["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]
	]],
	["AM1 - AT", [
		["rhs_weap_m4a1_blockII_d","","","rhsusf_acc_eotech_552_d",["rhs_mag_30Rnd_556x45_Mk318_PMAG",30],[],""],
		["launch_O_Titan_short_F","","","",["Titan_AT",1],[],""],
		["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],
		["rhs_uniform_cu_ocp",[["ACE_tourniquet",4],["ACE_morphine",4],["ACE_epinephrine",1],["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_quikclot",9],["ACE_elasticBandage",2]]],
		["rhsusf_iotv_ocp_Rifleman",[["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_splint",4],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_personalAidKit",1],["ItemcTabHCam",1],["ACRE_PRC343",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["MS_Strobe_Mag_1",5,1],["SmokeShell",6,1],["rhs_mag_m67",2,1],["rhs_mag_30Rnd_556x45_Mk318_PMAG",3,30]]],
		["B_Carryall_cbr",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",11,30],["Titan_AT",2,1]]],
		"rhsusf_ach_helmet_ocp",
		"",
		["Rangefinder","","","",[],[],""],
		["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]
	]],
	["AM1 - Designated Marksman", [
		["arifle_SPAR_03_blk_F","","","rhsusf_acc_su230a",["ACE_20Rnd_762x51_Mk319_Mod_0_Mag",20],[],"bipod_01_F_blk"],
		[],
		["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],
		["rhs_uniform_cu_ocp",[["ACE_tourniquet",4],["ACE_morphine",4],["ACE_epinephrine",1],["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_quikclot",9],["ACE_elasticBandage",2]]],
		["rhsusf_iotv_ocp_Rifleman",[["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_splint",4],["ACE_CableTie",6],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_personalAidKit",1],["ACRE_PRC343",1],["ItemcTabHCam",1],["ACE_RangeCard",1],["rhsusf_acc_aac_762sd_silencer",1],["rhsusf_mag_17Rnd_9x19_FMJ",3,17],["MS_Strobe_Mag_1",5,1],["SmokeShell",7,1],["rhs_mag_m67",3,1]]],
		["rhsusf_assault_eagleaiii_ocp",[["ACE_20Rnd_762x51_Mk319_Mod_0_Mag",16,20]]],
		"rhsusf_ach_helmet_ocp",
		"",
		["Rangefinder","","","",[],[],""],
		["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]
	]]
]